version: "3.9"

services:
  finalscheduler:
    build: ./FinalScheduler
    container_name: finalscheduler-FinalScheduler
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - redis
    networks:
      - final-network
    volumes:
      - ./FinalScheduler:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  node-backend:
    build: ./node-backend
    container_name: finalscheduler-node-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    networks:
      - final-network
    volumes:
      - ./node-backend:/app
      - /app/node_modules       
    command: npm start            
    restart: always
  mongodb:
    image: mongo:6
    container_name: finalscheduler-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - final-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  redis:
    image: redis:7
    container_name: finalscheduler-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - final-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  mongo_data:

networks:
  final-network:
    driver: bridge
